#!/bin/bash

if [ "$FILECHECKER_SH" == "1" ]
then

  function utils_valign
  {
    local I=0

    utils_clear
    while [ ${I} -ne ${ROWS_BEFORE} ]
    do
      echo ""
      (( I += 1 ))
    done
  }

  function display_splash_screen
  {
    local ROWS=`tput lines` LEN MARGIN MARGINSPACE

    LEN=40
    (( MARGIN= (${COLUMNS} - ${LEN}) / 2 ))
    MARGINSPACE="$(printf "%"${MARGIN}"s" " ")"
    if [ "${ROWS}" == "" ]
    then
      ROWS=40
    fi
    local ROWS_BEFORE=$(( ${ROWS} / 2 - 9 ))

    [ "${GLOBAL_LOCALBRANCH}" != "master" -o "${GLOBAL_IS_INTERACTIVE}" == "0" ] && return

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   .                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.052s

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.054s

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.056s

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                  |#|                   "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.058s

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                  /#\\                   "
    display_splash_screen_center_text "                 |###|                  "
    display_splash_screen_center_text "                  \\#/                   "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.06s

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                  /#\\                   "
    display_splash_screen_center_text "                 /###\\                  "
    display_splash_screen_center_text "                |#### |                 "
    display_splash_screen_center_text "                 \\###/                  "
    display_splash_screen_center_text "                  \\ /                   "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.062s

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                  / \\                   "
    display_splash_screen_center_text "                 /###\\                  "
    display_splash_screen_center_text "                /#### \\                 "
    display_splash_screen_center_text "               |#####  |                "
    display_splash_screen_center_text "                \\#### /                 "
    display_splash_screen_center_text "                 \\   /                  "
    display_splash_screen_center_text "                  \\#/                   "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.064s

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                  / \\                   "
    display_splash_screen_center_text "                 /   \\                  "
    display_splash_screen_center_text "                /#### \\                 "
    display_splash_screen_center_text "               /#####  \\                "
    display_splash_screen_center_text "              |######   |               "
    display_splash_screen_center_text "               \\#####  /                "
    display_splash_screen_center_text "                \\     /                 "
    display_splash_screen_center_text "                 \\###/                  "
    display_splash_screen_center_text "                  \\#/                   "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.066s

    utils_valign
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                  / \\                   "
    display_splash_screen_center_text "                 /  #\\                  "
    display_splash_screen_center_text "                /     \\                 "
    display_splash_screen_center_text "               /#####  \\                "
    display_splash_screen_center_text "              /######   \\               "
    display_splash_screen_center_text "             |#######    |              "
    display_splash_screen_center_text "              \\######   /               "
    display_splash_screen_center_text "               \\       /                "
    display_splash_screen_center_text "                \\#### /                 "
    display_splash_screen_center_text "                 \\###/                  "
    display_splash_screen_center_text "                  \\#/                   "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    display_splash_screen_center_text "                                        "
    sleep 0.068s

    utils_valign
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                  / \\                   "
    display_splash_screen_center_text "                 /  #\\                  "
    display_splash_screen_center_text "                /   ##\\                 "
    display_splash_screen_center_text "               /       \\                "
    display_splash_screen_center_text "              /######   \\               "
    display_splash_screen_center_text "             /#######    \\              "
    display_splash_screen_center_text "            |########     |             "
    display_splash_screen_center_text "             \\#######    /              "
    display_splash_screen_center_text "              \\         /               "
    display_splash_screen_center_text "               \\#####  /                "
    display_splash_screen_center_text "                \\#### /                 "
    display_splash_screen_center_text "                 \\###/                  "
    display_splash_screen_center_text "                  \\ /                   "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                                        "
    sleep 0.07s

    utils_valign
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                  / \\                   "
    display_splash_screen_center_text "                 /   \\                  "
    display_splash_screen_center_text "                /   ##\\                 "
    display_splash_screen_center_text "               /    ###\\                "
    display_splash_screen_center_text "              /         \\               "
    display_splash_screen_center_text "             /#######    \\              "
    display_splash_screen_center_text "            /########     \\             "
    display_splash_screen_center_text "           |#########      |            "
    display_splash_screen_center_text "            \\########     /             "
    display_splash_screen_center_text "             \\           /              "
    display_splash_screen_center_text "              \\######   /               "
    display_splash_screen_center_text "               \\#####  /                "
    display_splash_screen_center_text "                \\#### /                 "
    display_splash_screen_center_text "                 \\   /                  "
    display_splash_screen_center_text "                  \\ /                   "
    display_splash_screen_center_text "                   |                    "
    display_splash_screen_center_text "                   |                    "
    sleep 0.072s

    utils_valign
    display_splash_screen_center_text "                  / \\                   "
    display_splash_screen_center_text "                 /   \\                  "
    display_splash_screen_center_text "                /     \\                 "
    display_splash_screen_center_text "               /    ###\\                "
    display_splash_screen_center_text "              /     ####\\               "
    display_splash_screen_center_text "             /           \\              "
    display_splash_screen_center_text "            /########     \\             "
    display_splash_screen_center_text "           /#########      \\            "
    display_splash_screen_center_text "          |##########       |           "
    display_splash_screen_center_text "           \\#########      /            "
    display_splash_screen_center_text "            \\             /             "
    display_splash_screen_center_text "             \\#######    /              "
    display_splash_screen_center_text "              \\######  #/               "
    display_splash_screen_center_text "               \\#####  /                "
    display_splash_screen_center_text "                \\     /                 "
    display_splash_screen_center_text "                 \\   /                  "
    display_splash_screen_center_text "                  \\ /                   "
    display_splash_screen_center_text "                   |                    "
    sleep 0.074s

    utils_valign
    display_splash_screen_center_text "                 /   \\                  "
    display_splash_screen_center_text "                /     \\                 "
    display_splash_screen_center_text "               /      #\\                "
    display_splash_screen_center_text "              /     ####\\               "
    display_splash_screen_center_text "             /      #####\\              "
    display_splash_screen_center_text "            /             \\             "
    display_splash_screen_center_text "           /#########      \\            "
    display_splash_screen_center_text "          /##########       \\           "
    display_splash_screen_center_text "         |###########        |          "
    display_splash_screen_center_text "          \\##########       /           "
    display_splash_screen_center_text "           \\               /            "
    display_splash_screen_center_text "            \\ #######     /             "
    display_splash_screen_center_text "             \\#######   #/              "
    display_splash_screen_center_text "              \\######   /               "
    display_splash_screen_center_text "               \\       /                "
    display_splash_screen_center_text "                \\     /                 "
    display_splash_screen_center_text "                 \\   /                  "
    display_splash_screen_center_text "                  \\ /                   "
    sleep 0.076s

    utils_valign
    display_splash_screen_center_text "                /     \\                 "
    display_splash_screen_center_text "               /       \\                "
    display_splash_screen_center_text "              /       ##\\               "
    display_splash_screen_center_text "             /      #####\\              "
    display_splash_screen_center_text "            /       ######\\             "
    display_splash_screen_center_text "           /               \\            "
    display_splash_screen_center_text "          /##########       \\           "
    display_splash_screen_center_text "         /###########        \\          "
    display_splash_screen_center_text "        |############         |         "
    display_splash_screen_center_text "         \\###########        /          "
    display_splash_screen_center_text "          \\                 /           "
    display_splash_screen_center_text "           \\  #######     #/            "
    display_splash_screen_center_text "            \\ #######   ##/             "
    display_splash_screen_center_text "             \\#######   #/              "
    display_splash_screen_center_text "              \\         /               "
    display_splash_screen_center_text "               \\       /                "
    display_splash_screen_center_text "                \\     /                 "
    display_splash_screen_center_text "                 \\   /                  "
    sleep 0.08s

    utils_valign
    display_splash_screen_center_text "               /       \\                "
    display_splash_screen_center_text "              /         \\               "
    display_splash_screen_center_text "             /        ###\\              "
    display_splash_screen_center_text "            /       ######\\             "
    display_splash_screen_center_text "           /        #######\\            "
    display_splash_screen_center_text "          /                #\\           "
    display_splash_screen_center_text "         /###########      ##\\          "
    display_splash_screen_center_text "        /############         \\         "
    display_splash_screen_center_text "       |#############          |        "
    display_splash_screen_center_text "        \\############         /         "
    display_splash_screen_center_text "         \\                  #/          "
    display_splash_screen_center_text "          \\   #######     ##/           "
    display_splash_screen_center_text "           \\  #######   ###/            "
    display_splash_screen_center_text "            \\ #######   ##/             "
    display_splash_screen_center_text "             \\          #/              "
    display_splash_screen_center_text "              \\         /               "
    display_splash_screen_center_text "               \\       /                "
    display_splash_screen_center_text "                \\     /                 "
    sleep 0.015s

    utils_valign
    display_splash_screen_center_text "              /         \\               "
    display_splash_screen_center_text "             /          #\\              "
    display_splash_screen_center_text "            /         ####\\             "
    display_splash_screen_center_text "           /        #######\\            "
    display_splash_screen_center_text "          /         ########\\           "
    display_splash_screen_center_text "         /                 ##\\          "
    display_splash_screen_center_text "        /############      ###\\         "
    display_splash_screen_center_text "       /#############          \\        "
    display_splash_screen_center_text "      |##############           |       "
    display_splash_screen_center_text "       \\#############         #/        "
    display_splash_screen_center_text "        \\                   ##/         "
    display_splash_screen_center_text "         \\    #######     ###/          "
    display_splash_screen_center_text "          \\   #######   ####/           "
    display_splash_screen_center_text "           \\  #######   ###/            "
    display_splash_screen_center_text "            \\           ##/             "
    display_splash_screen_center_text "             \\          #/              "
    display_splash_screen_center_text "              \\         /               "
    display_splash_screen_center_text "               \\       /                "
    sleep 0.024s

    utils_valign
    display_splash_screen_center_text "             /           \\              "
    display_splash_screen_center_text "            /           ##\\             "
    display_splash_screen_center_text "           /          #### \\            "
    display_splash_screen_center_text "          /         ########\\           "
    display_splash_screen_center_text "         /          #########\\          "
    display_splash_screen_center_text "        /                  ###\\         "
    display_splash_screen_center_text "       /#############      ####\\        "
    display_splash_screen_center_text "      /##############           \\       "
    display_splash_screen_center_text "     |###############            |      "
    display_splash_screen_center_text "      \\##############         ##/       "
    display_splash_screen_center_text "       \\                    ###/        "
    display_splash_screen_center_text "        \\     #######     ####/         "
    display_splash_screen_center_text "         \\    #######   #####/          "
    display_splash_screen_center_text "          \\   #######   ####/           "
    display_splash_screen_center_text "           \\            ###/            "
    display_splash_screen_center_text "            \\           ##/             "
    display_splash_screen_center_text "             \\          #/              "
    display_splash_screen_center_text "              \\         /               "
    sleep 0.029s

    utils_valign
    display_splash_screen_center_text "            /             \\             "
    display_splash_screen_center_text "           /            ###\\            "
    display_splash_screen_center_text "          /           ####  \\           "
    display_splash_screen_center_text "         /          #########\\          "
    display_splash_screen_center_text "        /           ##########\\         "
    display_splash_screen_center_text "       /                   ####\\        "
    display_splash_screen_center_text "      /##############      #### \\       "
    display_splash_screen_center_text "     /###############            \\      "
    display_splash_screen_center_text "    |################             |     "
    display_splash_screen_center_text "     \\###############         ###/      "
    display_splash_screen_center_text "      \\                     ####/       "
    display_splash_screen_center_text "       \\      #######     #####/        "
    display_splash_screen_center_text "        \\     #######   ######/         "
    display_splash_screen_center_text "         \\    #######   #####/          "
    display_splash_screen_center_text "          \\             ####/           "
    display_splash_screen_center_text "           \\            ###/            "
    display_splash_screen_center_text "            \\           ##/             "
    display_splash_screen_center_text "             \\          #/              "
    sleep 0.035s

    utils_valign
    display_splash_screen_center_text "           /              #\\            "
    display_splash_screen_center_text "          /             ####\\           "
    display_splash_screen_center_text "         /            ####   \\          "
    display_splash_screen_center_text "        /           ##########\\         "
    display_splash_screen_center_text "       /            ###########\\        "
    display_splash_screen_center_text "      /                    #### \\       "
    display_splash_screen_center_text "     /###############      ####  \\      "
    display_splash_screen_center_text "    /################             \\     "
    display_splash_screen_center_text "   |#################              |    "
    display_splash_screen_center_text "    \\################         ####/     "
    display_splash_screen_center_text "     \\#                     #####/      "
    display_splash_screen_center_text "      \\       #######     ######/       "
    display_splash_screen_center_text "       \\      #######   #######/        "
    display_splash_screen_center_text "        \\     #######   ##### /         "
    display_splash_screen_center_text "         \\              #####/          "
    display_splash_screen_center_text "          \\             ####/           "
    display_splash_screen_center_text "           \\            ###/            "
    display_splash_screen_center_text "            \\           ##/.            "
    sleep 0.041s

    utils_valign
    display_splash_screen_center_text "          /               ##\\           "
    display_splash_screen_center_text "         /              #### \\          "
    display_splash_screen_center_text "        /             ####    \\         "
    display_splash_screen_center_text "       /            ###########\\        "
    display_splash_screen_center_text "      /             ########### \\       "
    display_splash_screen_center_text "     /                     ####  \\      "
    display_splash_screen_center_text "    /################      ####   \\     "
    display_splash_screen_center_text "   /#################              \\    "
    display_splash_screen_center_text "  |##################               |   "
    display_splash_screen_center_text "   \\#################         #####/    "
    display_splash_screen_center_text "    \\##                     ######/     "
    display_splash_screen_center_text "     \\#       #######     #######/      "
    display_splash_screen_center_text "      \\       #######   ########/       "
    display_splash_screen_center_text "       \\      #######   ###### /        "
    display_splash_screen_center_text "        \\               ##### /         "
    display_splash_screen_center_text "         \\              #####/          "
    display_splash_screen_center_text "          \\             ####/           "
    display_splash_screen_center_text "           \\            ###/            "
    sleep 0.046s

    utils_valign
    display_splash_screen_center_text "         /                ###\\          "
    display_splash_screen_center_text "        /               ####  \\         "
    display_splash_screen_center_text "       /              ####     \\        "
    display_splash_screen_center_text "      /             ########### \\       "
    display_splash_screen_center_text "     /              ########### #\\      "
    display_splash_screen_center_text "    /                      ####   \\     "
    display_splash_screen_center_text "   /#################      ####    \\    "
    display_splash_screen_center_text "  /##################               \\   "
    display_splash_screen_center_text " |###################                |  "
    display_splash_screen_center_text "  \\##################         ######/   "
    display_splash_screen_center_text "   \\###                     #######/    "
    display_splash_screen_center_text "    \\##       #######     ########/     "
    display_splash_screen_center_text "     \\#       #######   ######## /      "
    display_splash_screen_center_text "      \\       #######   ######  /       "
    display_splash_screen_center_text "       \\                #####  /        "
    display_splash_screen_center_text "        \\               ##### /         "
    display_splash_screen_center_text "         \\              #####/          "
    display_splash_screen_center_text "          \\             ####/           "
    sleep 0.051s

    utils_valign
    display_splash_screen_center_text "        /                 ####\\         "
    display_splash_screen_center_text "       /                ####   \\        "
    display_splash_screen_center_text "      /               ####      \\       "
    display_splash_screen_center_text "     /              ########### #\\      "
    display_splash_screen_center_text "    /               ########### ##\\     "
    display_splash_screen_center_text "   /                       ####    \\    "
    display_splash_screen_center_text "  /##################      ####     \\   "
    display_splash_screen_center_text " /###################                \\  "
    display_splash_screen_center_text "|####################                 | "
    display_splash_screen_center_text " \\###################         #######/  "
    display_splash_screen_center_text "  \\####                     ####### /   "
    display_splash_screen_center_text "   \\###       #######     ######## /    "
    display_splash_screen_center_text "    \\##       #######   ########  /     "
    display_splash_screen_center_text "     \\#       #######   ######   /      "
    display_splash_screen_center_text "      \\                 #####   /       "
    display_splash_screen_center_text "       \\                #####  /        "
    display_splash_screen_center_text "        \\               ##### /         "
    display_splash_screen_center_text "         \\              #####/          "
    sleep 0.055s

    utils_valign
    display_splash_screen_center_text "       /                  #### \\        "
    display_splash_screen_center_text "      /                 ####    \\       "
    display_splash_screen_center_text "     /                ####       \\      "
    display_splash_screen_center_text "    /               ########### ##\\     "
    display_splash_screen_center_text "   /                ########### ###\\    "
    display_splash_screen_center_text "  /                        ####     \\   "
    display_splash_screen_center_text " /###################      ####      \\  "
    display_splash_screen_center_text "/####################                 \\ "
    display_splash_screen_center_text "#####################                  |"
    display_splash_screen_center_text "\\####################         ####### / "
    display_splash_screen_center_text " \\#####                     #######  /  "
    display_splash_screen_center_text "  \\####       #######     ########  /   "
    display_splash_screen_center_text "   \\###       #######   ########   /    "
    display_splash_screen_center_text "    \\##       #######   ######    /     "
    display_splash_screen_center_text "     \\#                 #####    /      "
    display_splash_screen_center_text "      \\                 #####   /       "
    display_splash_screen_center_text "       \\                #####  /        "
    display_splash_screen_center_text "        \\               ##### /         "
    sleep 0.059s

    utils_valign
    display_splash_screen_center_text "      /                   ####  \\       "
    display_splash_screen_center_text "     /                  ####    #\\      "
    display_splash_screen_center_text "    /                 ####        \\     "
    display_splash_screen_center_text "   /                ########### ###\\    "
    display_splash_screen_center_text "  /                 ########### ####\\   "
    display_splash_screen_center_text " /                         ####      \\  "
    display_splash_screen_center_text "/####################      ####       \\ "
    display_splash_screen_center_text "#####################                  \\"
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######  /"
    display_splash_screen_center_text "\\######                     #######   / "
    display_splash_screen_center_text " \\#####       #######     ########   /  "
    display_splash_screen_center_text "  \\####       #######   ########    /   "
    display_splash_screen_center_text "   \\###       #######   ######     /    "
    display_splash_screen_center_text "    \\##                 #####     /     "
    display_splash_screen_center_text "     \\#                 #####    /      "
    display_splash_screen_center_text "      \\                 #####   /       "
    display_splash_screen_center_text "       \\                #####  /        "
    sleep 0.062s

    utils_valign
    display_splash_screen_center_text "     /                    ####  #\\      "
    display_splash_screen_center_text "    /                   ####    ##\\     "
    display_splash_screen_center_text "   /                  ####        #\\    "
    display_splash_screen_center_text "  /                 ########### ####\\   "
    display_splash_screen_center_text " /                  ########### #####\\  "
    display_splash_screen_center_text "/                          ####       \\ "
    display_splash_screen_center_text "#####################      ####        \\"
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######    /"
    display_splash_screen_center_text "\\######       #######     ########    / "
    display_splash_screen_center_text " \\#####       #######   ########     /  "
    display_splash_screen_center_text "  \\####       #######   ######      /   "
    display_splash_screen_center_text "   \\###                 #####      /    "
    display_splash_screen_center_text "    \\##                 #####     /     "
    display_splash_screen_center_text "     \\#                 #####    /      "
    display_splash_screen_center_text "      \\                 #####   /       "
    sleep 0.065s

    utils_valign
    display_splash_screen_center_text "    /                     ####  ##\\     "
    display_splash_screen_center_text "   /                    ####    ## \\    "
    display_splash_screen_center_text "  /                   ####        ##\\   "
    display_splash_screen_center_text " /                  ########### #####\\  "
    display_splash_screen_center_text "/                   ########### ######\\ "
    display_splash_screen_center_text "                           ####        \\"
    display_splash_screen_center_text "#####################      ####         "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######     "
    display_splash_screen_center_text "#######       #######     ########     /"
    display_splash_screen_center_text "\\######       #######   ########      / "
    display_splash_screen_center_text " \\#####       #######   ######       /  "
    display_splash_screen_center_text "  \\####                 #####       /   "
    display_splash_screen_center_text "   \\###                 #####      /    "
    display_splash_screen_center_text "    \\##                 #####     /     "
    display_splash_screen_center_text "     \\#                 #####   #/      "
    sleep 0.068s

    utils_valign
    display_splash_screen_center_text "   /                      ####  ###\\    "
    display_splash_screen_center_text "  /                     ####    ##  \\   "
    display_splash_screen_center_text " /                    ####        ###\\  "
    display_splash_screen_center_text "/                   ########### ##### \\ "
    display_splash_screen_center_text "                    ########### #######\\"
    display_splash_screen_center_text "                           ####         "
    display_splash_screen_center_text "#####################      ####         "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######     "
    display_splash_screen_center_text "#######       #######     ########      "
    display_splash_screen_center_text "#######       #######   ########       /"
    display_splash_screen_center_text "\\######       #######   ######        / "
    display_splash_screen_center_text " \\#####                 #####        /  "
    display_splash_screen_center_text "  \\####                 #####       /   "
    display_splash_screen_center_text "   \\###                 #####     #/    "
    display_splash_screen_center_text "    \\##                 #####   ##/     "
    sleep 0.07s

    utils_valign
    display_splash_screen_center_text "  /                       ####  ####\\   "
    display_splash_screen_center_text " /                      ####    ##  #\\  "
    display_splash_screen_center_text "/                     ####        ####\\ "
    display_splash_screen_center_text "                    ########### #####  \\"
    display_splash_screen_center_text "                    ########### ########"
    display_splash_screen_center_text "                           ####         "
    display_splash_screen_center_text "#####################      ####         "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######     "
    display_splash_screen_center_text "#######       #######     ########      "
    display_splash_screen_center_text "#######       #######   ########        "
    display_splash_screen_center_text "#######       #######   ######         /"
    display_splash_screen_center_text "\\######                 #####         / "
    display_splash_screen_center_text " \\#####                 #####       #/  "
    display_splash_screen_center_text "  \\####                 #####     ##/   "
    display_splash_screen_center_text "   \\###                 #####   ###/    "
    sleep 0.072s

    utils_valign
    display_splash_screen_center_text " /                        ####  #####\\  "
    display_splash_screen_center_text "/                       ####    ##  ##\\ "
    display_splash_screen_center_text "                      ####        #####\\"
    display_splash_screen_center_text "                    ########### #####  #"
    display_splash_screen_center_text "                    ########### ########"
    display_splash_screen_center_text "                           ####         "
    display_splash_screen_center_text "#####################      ####         "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######     "
    display_splash_screen_center_text "#######       #######     ########      "
    display_splash_screen_center_text "#######       #######   ########        "
    display_splash_screen_center_text "#######       #######   ######          "
    display_splash_screen_center_text "#######                 #####         #/"
    display_splash_screen_center_text "\\######                 #####       ##/ "
    display_splash_screen_center_text " \\#####                 #####     ###/  "
    display_splash_screen_center_text "  \\####                 #####   ####/   "
    sleep 0.074s

    utils_valign
    display_splash_screen_center_text "/                         ####  ######\\ "
    display_splash_screen_center_text "                        ####    ##  ###\\"
    display_splash_screen_center_text "                      ####        ##### "
    display_splash_screen_center_text "                    ########### #####  #"
    display_splash_screen_center_text "                    ########### ########"
    display_splash_screen_center_text "                           ####         "
    display_splash_screen_center_text "#####################      ####         "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######     "
    display_splash_screen_center_text "#######       #######     ########      "
    display_splash_screen_center_text "#######       #######   ########        "
    display_splash_screen_center_text "#######       #######   ######          "
    display_splash_screen_center_text "#######                 #####         ##"
    display_splash_screen_center_text "#######                 #####       ###/"
    display_splash_screen_center_text "\\######                 #####     ####/ "
    display_splash_screen_center_text " \\#####                 #####   #####/  "
    sleep 0.076s

    utils_valign
    display_splash_screen_center_text "                          ####  #######\\"
    display_splash_screen_center_text "                        ####    ##  ####"
    display_splash_screen_center_text "                      ####        ##### "
    display_splash_screen_center_text "                    ########### #####  #"
    display_splash_screen_center_text "                    ########### ########"
    display_splash_screen_center_text "                           ####         "
    display_splash_screen_center_text "#####################      ####         "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######     "
    display_splash_screen_center_text "#######       #######     ########      "
    display_splash_screen_center_text "#######       #######   ########        "
    display_splash_screen_center_text "#######       #######   ######          "
    display_splash_screen_center_text "#######                 #####         ##"
    display_splash_screen_center_text "#######                 #####       ####"
    display_splash_screen_center_text "#######                 #####     #####/"
    display_splash_screen_center_text "\\######                 #####   ######/ "
    sleep 0.078s

    utils_valign
    display_splash_screen_center_text "                          ####  ########"
    display_splash_screen_center_text "                        ####    ##  ####"
    display_splash_screen_center_text "                      ####        ##### "
    display_splash_screen_center_text "                    ########### #####  #"
    display_splash_screen_center_text "                    ########### ########"
    display_splash_screen_center_text "                           ####         "
    display_splash_screen_center_text "#####################      ####         "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######     "
    display_splash_screen_center_text "#######       #######     ########      "
    display_splash_screen_center_text "#######       #######   ########        "
    display_splash_screen_center_text "#######       #######   ######          "
    display_splash_screen_center_text "#######                 #####         ##"
    display_splash_screen_center_text "#######                 #####       ####"
    display_splash_screen_center_text "#######                 #####     ######"
    display_splash_screen_center_text "#######                 #####   #######/"
    sleep 0.08s

    utils_valign
    display_splash_screen_center_text "                          ####  ########"
    display_splash_screen_center_text "                        ####    ##  ####"
    display_splash_screen_center_text "                      ####        ##### "
    display_splash_screen_center_text "                    ########### #####  #"
    display_splash_screen_center_text "                    ########### ########"
    display_splash_screen_center_text "                           ####         "
    display_splash_screen_center_text "#####################      ####         "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################                   "
    display_splash_screen_center_text "#####################         #######   "
    display_splash_screen_center_text "#######                     #######     "
    display_splash_screen_center_text "#######       #######     ########      "
    display_splash_screen_center_text "#######       #######   ########        "
    display_splash_screen_center_text "#######       #######   ######          "
    display_splash_screen_center_text "#######                 #####         ##"
    display_splash_screen_center_text "#######                 #####       ####"
    display_splash_screen_center_text "#######                 #####     ######"
    display_splash_screen_center_text "#######                 #####   ########"
    sleep 1s

    printf "${C_CLEAR}"
  }

  function display_splash_screen_center_text
  {
    printf "%s${C_RED}%s${C_CLEAR}\n" "${MARGINSPACE}" "${1}"
  }

fi
